### ISSUE TITLE
Capture picking log

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#156]
One day we will want statistics on picking, especially the time taken and order or picks/edits. 

Seems like the easiest way to do this is just to capture a log of every picking event... @stevejpurves , probably one for you??

One day (soon?) we will want to show, for example, a histogram of time taken for picking, or the number of point picks and moves, or perhaps even to be able to replay every interpretation in real (or double?) time.

**Comment by stevejpurves** [comment]
got basic picking history. need to add timestamps.

**Comment by stevejpurves** [comment]
think this is done, just need to do something with the logs next
