### ISSUE TITLE
DeadlineExceededError critical bug

### ISSUE THREAD

**Issue by ben-bougher** [agile-geoscience/pickr#170]
This was the error from the logs. Looks like maybe the dilate algorithm is choking?

    y[mh+x[i,0]:mh+x[i,0]+h, mw+x[i,1]:mw+x[i,1]+w], add4dilate(f,v[i]))
    DeadlineExceededError

**Comment by kwinkunks** [comment]
Hm, might be a red herring. I'm seeing it in /library, which doesn't invoke the heatmap. The picks aren't exactly huge data, so I'll be surprised if that is the problem.

I got /about to render, and it hits the database (for counts). 

Seeing things like this:

    user_ids = [p.user_id for p in picks]

    img_objs = ImageObject.all().ancestor(db_parent).filter("title !=", '').fetch(10000)

Is this the latency / database traffic clobbering us? Huge latency on Instance 1 of 4:
https://www.dropbox.com/s/gi84o8jiy0wkzh6/Screenshot%202015-02-24%2021.08.54.png?dl=0

@ben-bougher can you add this bit of configuration to the app.yaml file? 
https://cloud.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Warmup_requests

It sounds like that will help the latency issue at least.

**Comment by kwinkunks** [comment]
Finally `/library` loaded, and I even got some results pages to load (eg brain and photomicrograph and even hohoho with 51 interpretations), but indeed I am now getting the error from `add4dilate` too.

**Comment by kwinkunks** [comment]
Fewer errors today, but they are still happening. All of the last few have been waiting for `add4dilate`. Linked to #88.

**Comment by kwinkunks** [comment]
I think 961481845ba755779eeb0ce88ee7467281d526d0 will go a long way to fixing this until we do #164
