### ISSUE TITLE
Signout error

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#174]
Not a huge deal, seems to be on dev only. 

**On dev server** — If I sign out from a Results page, I get an error.

**On prod server** — No problem

**Comment by JesperDramsch** [comment]
I had an error when logging in on *prod* in the recent version. Reloading the library works afterwards.

**Comment by kwinkunks** [comment]
We are experiencing some performance issues and resulting timeouts in prod.

The recent heatmap caching fix from Steve will improve it... I think we
should deploy this soon...

/m

**Comment by stevejpurves** [comment]
I saw that error intermittently when running a local dev server too.

**Comment by kwinkunks** [comment]
I think this is fixed.
