### ISSUE TITLE
Critical bug: Heatmap index out of bounds

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#176]
I can't get some of the heatmaps to render. Spinner forever.

This on Brain:
https://www.dropbox.com/s/7kjjduqidap1dtp/Screenshot%202015-03-04%2007.46.28.png?dl=0

Sobrarbe also never loads. Got DeadlineExceeded:
https://www.dropbox.com/s/he6qvdq58z2b748/Screenshot%202015-03-04%2007.45.45.png?dl=0

Ho ho ho, DeadlineExceeded again: 
https://www.dropbox.com/s/abkqerrfx4mqews/Screenshot%202015-03-04%2007.49.27.png?dl=0

Loading OK: Ankle, Marmousi, Flatspot (all from heatmap generation I think) and NS, Alaska, Brazil from cache.

**Comment by kwinkunks** [comment]
Almost everything is working today, except Brain, see #179

**Comment by stevejpurves** [comment]
this should be resolved with the last merge

**Comment by kwinkunks** [comment]
Awesome, thank you Steve :)
