### ISSUE TITLE
heatmaps not generating as expected

### ISSUE THREAD

**Issue by stevejpurves** [agile-geoscience/pickr#200]
something wrong with heatmap compositing, when a new user adds a pick.

Maybe normalisation not being applied properly, as each pick appears to have its own 'level' in the image. What is curious is that when an admin regenerates all heatmaps, then we get the expected heatmap. 

So something different (and wrong) is happening when only a single layer for the new pick is added.

**Comment by stevejpurves** [comment]
essential to fix before next deploy

**Comment by kwinkunks** [comment]
Steve can you get us a screenshot?

**Comment by ben-bougher** [comment]
We were essentially adding the previous heatmap when we were generating the new ones. The previous picks were being added in a bit of a feedback loop.
