### ISSUE TITLE
Multiple items

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#22]
As well as other geometries (see last issue), it would be good to allow the interpretation of multiple features... multiple lines (for multiple faults), multiple points (almost a prerequisite for that geometry) and multiple polygons.

The idea would be that clicking a certain distance from an existing point (or any distance, for points), would be interpreted as starting a new object.

**Comment by kwinkunks** [comment]
I think this is one for @stevejpurves — he's the Raphael guru around here.

**Comment by stevejpurves** [comment]
#195 gets a good first pass on this. Will merge that now.

Lets take it for a spin and get it deployed :) feedback on the visual changes would be good.

an outstanding todos (or further enhancements) is to add some type of double-click/double-tap handling that works nicely for desktops and mobile as well as the new pick button. Oh and update help

**Comment by kwinkunks** [comment]
Essentially all taken care of — new features may include allowing multiple feature types in one interpretation, or labelling / colouring features. See #220.
