### ISSUE TITLE
Points not placed where clicked

### ISSUE THREAD

**Issue by mtb-za** [agile-geoscience/pickr#222]
I decided to pick some stuff as a bit of downtime today, and picked a section from nearby: http://pickthis.io/pickr?image_key=5491672892833792

However, the placement of the points for the lines is totally out from where I am clicking. I checked on another image, and this is consistent (although the offset is not).

The blue line is approximately where I am clicking, while the red line is where my pick is appearing.

![2015-09-14-140351_1920x1848_scrot](https://cloud.githubusercontent.com/assets/1148889/9849349/7f455f28-5aea-11e5-91bd-09403d62232a.png)
![2015-09-14-141727_1920x1848_scrot](https://cloud.githubusercontent.com/assets/1148889/9849468/95aa682a-5aeb-11e5-8cea-d57bf23fcee1.png)

This also happens when picking points:
![2015-09-14-142611_1920x1848_scrot](https://cloud.githubusercontent.com/assets/1148889/9849621/c9e6c448-5aec-11e5-915f-caa0311de737.png)

Any idea if this is something from my end?

Some details of my setup.
    Linux 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
    Firefox 40.0.3-1

Let me know if I can supply any more information.

**Comment by stevejpurves** [comment]
Hi Martin, picking works in firefox 34.x but after upgrading to 40.0 its broken, I can reproduce what you are seeing! look like something has changed with firefox. gonna convert this to a bug and thanks for reporting that issue!

**Comment by mtb-za** [comment]
No worries. Weird error though, so I wonder what they did....

**Comment by kwinkunks** [comment]
We had trouble like this early on — it's a change, I guess, in how the coordinates come back to the back end. On-screen pixels vs in-image pixels. Not sure how we'll scrub this stuff out of the database...

**Comment by stevejpurves** [comment]
have just pushed a fix, think there must have been a change in firefox's mouse events somewhere down the line.

**Comment by mtb-za** [comment]
This seems to be working correctly now, thanks a lot.

**Comment by stevejpurves** [comment]
awesome, thanks to @ben-bougher for pushing the changes. 
Still leaves the question issue that we might have accidental junk picks in there now though cc @matt

**Comment by kwinkunks** [comment]
@stevejpurves From what I can tell, there's nothing on the images to suggest these caused a problem — at least nothing that looks like the things @mtb-za kindly screenshotted... If anyone *did* submit broken picks, then I guess it was just the Raphael plotting that 'misunderstood' the coordinates, and the heatmap stuff was OK...?
