### ISSUE TITLE
Refactor heatmap generation

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#88]
Right now we generate the heatmap 'from scratch' every time someone wants to see it. 

Instead, we could... 

1. Store it, so if a person just wants to see the results (without interpreting), we already have the static version.
1. Only add the new interpretation when someone adds one. So take the stored image, deal with the value scaling (or store the number of interpretations it contains... I guess we know that from the image anyway) and only add the new one.

**Comment by kwinkunks** [comment]
A good first step is probably only generating this image when someone picks it, then storing the generated PNG. This would speed things up quite a bit. 

We could cache it, but we're not hitting db bottlenecks / limits yet. 

Elevating to bug because some of the images are getting very laggy.

**Comment by kwinkunks** [comment]
Possibly causing #170.

**Comment by stevejpurves** [comment]
we're doing 1 already and seeing the current design being deficient for concurrent requests. That can be dealt with but option 2 adds more complexity, when trying to handle concurrent requests properly. Guess what I mean is that doing 2 will also mean some design / architecture change around it too.

**Comment by ben-bougher** [comment]
I think this is dealt with
